server:
  port: 9996
spring:
  application:
    name: api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

zuul:
  routes:
    route1:
      path: /provider/*
      service-id: provider


